import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


def _header_footer(canvas, doc):
    """Add page number footer to every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawCentredString(
        letter[0] / 2,
        0.5 * inch,
        f"Page {doc.page}  |  Generated by Policy Impact Engine",
    )
    canvas.restoreState()


def generate_pdf_report(
    simulation_name: str,
    summary_stats: dict,
    date_str: str,
) -> bytes:
    """Generate a PDF report and return it as bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()
    story: list = []

    # Custom styles
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.Color(0.3, 0.3, 0.3),
        spaceAfter=6,
    )
    section_style = ParagraphStyle(
        "SectionHead",
        parent=styles["Heading2"],
        textColor=colors.Color(0.15, 0.3, 0.55),
        spaceBefore=18,
        spaceAfter=8,
    )

    # ── Title ──
    story.append(Paragraph("Policy Impact Report", styles["Title"]))
    story.append(Paragraph(f"Simulation: {simulation_name}", styles["Heading2"]))
    story.append(Paragraph(f"Generated: {date_str}", subtitle_style))
    story.append(Spacer(1, 20))

    # ── Executive Summary ──
    story.append(Paragraph("Executive Summary", section_style))

    total = summary_stats.get("total_customers", 0)
    affected = summary_stats.get("affected_customers", 0)
    affected_pct = summary_stats.get("affected_percentage", 0)
    dc = summary_stats.get("decision_changes", {})

    exec_data = [
        ["Metric", "Value"],
        ["Total Customers Evaluated", _fmt(total)],
        ["Affected Customers", f"{_fmt(affected)} ({affected_pct}%)"],
        ["Approved \u2192 Rejected", _fmt(dc.get("approved_to_rejected", 0))],
        ["Rejected \u2192 Approved", _fmt(dc.get("rejected_to_approved", 0))],
        ["Baseline Approved", _fmt(dc.get("baseline_approved", 0))],
        ["Simulated Approved", _fmt(dc.get("simulated_approved", 0))],
    ]
    story.append(_make_table(exec_data))
    story.append(Spacer(1, 14))

    # ── Decision Changes ──
    story.append(Paragraph("Decision Changes", section_style))
    dc_data = [
        ["Direction", "Count"],
        ["Approved to Rejected", _fmt(dc.get("approved_to_rejected", 0))],
        ["Rejected to Approved", _fmt(dc.get("rejected_to_approved", 0))],
        ["Unchanged", _fmt(dc.get("unchanged", 0))],
    ]
    story.append(_make_table(dc_data))
    story.append(Spacer(1, 14))

    # ── Amount Changes ──
    ac = summary_stats.get("amount_changes", {})
    story.append(Paragraph("Amount &amp; Rate Changes", section_style))
    ac_data = [
        ["Metric", "Value"],
        ["Amount Increased", _fmt(ac.get("increased", 0))],
        ["Amount Decreased", _fmt(ac.get("decreased", 0))],
        ["Average Amount Delta", _fmt_money(ac.get("avg_delta", 0))],
        ["Total Amount Delta", _fmt_money(ac.get("total_delta", 0))],
        ["Rate Increased", _fmt(ac.get("rate_increased", 0))],
        ["Rate Decreased", _fmt(ac.get("rate_decreased", 0))],
        ["Avg Rate Delta (bps)", _fmt(ac.get("avg_rate_delta", 0))],
    ]
    story.append(_make_table(ac_data))
    story.append(Spacer(1, 14))

    # ── Segment Breakdown ──
    seg = summary_stats.get("segment_breakdown", {})
    if seg:
        story.append(Paragraph("Segment Breakdown", section_style))
        for seg_type, segments in seg.items():
            label = seg_type.replace("by_", "").replace("_", " ").title()
            story.append(Paragraph(f"By {label}", styles["Heading3"]))

            seg_data = [["Segment", "Total", "Affected", "Affected %"]]
            for name, vals in segments.items():
                seg_data.append([
                    str(name),
                    _fmt(vals.get("total", 0)),
                    _fmt(vals.get("affected", 0)),
                    f"{vals.get('affected_pct', 0)}%",
                ])
            story.append(_make_table(seg_data))
            story.append(Spacer(1, 10))

    # ── Financial Impact ──
    fi = summary_stats.get("financial_impact", {})
    if fi:
        story.append(Paragraph("Financial Impact", section_style))
        fi_data = [["Metric", "Value"]]
        display_map = {
            "total_baseline_exposure": ("Total Baseline Exposure", True),
            "total_simulated_exposure": ("Total Simulated Exposure", True),
            "exposure_change": ("Exposure Change", True),
            "exposure_change_pct": ("Exposure Change (%)", False),
            "estimated_revenue_baseline": ("Est. Revenue (Baseline)", True),
            "estimated_revenue_simulated": ("Est. Revenue (Simulated)", True),
            "revenue_impact": ("Revenue Impact", True),
            "avg_rate_baseline": ("Avg Rate (Baseline)", False),
            "avg_rate_simulated": ("Avg Rate (Simulated)", False),
        }
        for key, val in fi.items():
            label, is_money = display_map.get(key, (key.replace("_", " ").title(), False))
            fi_data.append([label, _fmt_money(val) if is_money else _fmt(val)])
        story.append(_make_table(fi_data))

    # Build the PDF
    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer.getvalue()


# ── Helper functions ──

def _fmt(value) -> str:
    """Format a numeric value for display."""
    if value is None:
        return "N/A"
    if isinstance(value, float):
        return f"{value:,.2f}"
    if isinstance(value, int):
        return f"{value:,}"
    return str(value)


def _fmt_money(value) -> str:
    """Format as currency."""
    if value is None:
        return "N/A"
    try:
        return f"${float(value):,.2f}"
    except (TypeError, ValueError):
        return str(value)


def _make_table(data: list[list]) -> Table:
    """Create a consistently styled ReportLab table."""
    table = Table(data, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.15, 0.3, 0.55)),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.Color(0.95, 0.95, 0.97), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.Color(0.8, 0.8, 0.8)),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return table
